<?php

$products = $block->getFeaturedProducts();

$showWishlist = true;
$showCompare = true;
$showCart = true;
?>

<?php if (empty($products)): ?>
    <div class="message info empty">
        <div><?= /* @noEscape */
            __('No Featured Product Found.') ?></div>
    </div>
<?php else: ?>
    <div class="risecommerce-featured-products-slider">
        <div class="risecommerce-featured-products-slider-container">
            <h1>Featured Products</h1>
            <div class="block widget block-products-list grid">
                <?php if ($block->getTitle()): ?>
                    <div class="block-title">
                        <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
                    </div>
                <?php endif ?>
                <div class="block-content">
                    <div class="products-grid grid">
                        <ol class="product-items widget-product-grid">
                            <div class="risecommerce_featured_products_product_slider">
                                <?php foreach ($products as $_product): ?>
                                    <?php $postParams = $block->getAddToCartPostParameters($_product); ?>
                                    <li class="product-item risecommercefeaturedproductsslider">
                                        <div class="product-item-info">
                                            <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                               class="product-item-photo">
                                            <span
                                                class="product-image-container risecommercefeaturedproductsslider-image-container">
                                                <span
                                                    class="product-image-wrapper risecommercefeaturedproductsslider-image-wrapper">
                                                    <img class="product-image-photo"
                                                         src="<?= $block->escapeHtmlAttr($block->getProductImage($_product->getImage())); ?>">
                                                </span>
                                            </span>
                                            </a>
                                            <div class="product-item-details">
                                                <strong class="product-item-name">
                                                    <a title="<?= $block->escapeHtml($_product->getName()) ?>"
                                                       href="<?= $block->escapeUrl($_product->getProductUrl($_product)) ?>"
                                                       class="product-item-link">
                                                        <?= $block->escapeHtml($_product->getName()) ?>
                                                    </a>
                                                </strong>
                                                <?php
                                                //pass $product object as argument...
                                                $_ratingSummary = $block->getRatingSummary($_product);
                                                $_reviewCount = $block->getReviewsCount($_product);
                                                ?>
                                                <?php if ($_ratingSummary) { ?>
                                                    <div class="product-reviews-summary short">
                                                        <div class="rating-summary">
                                                            <div title="<?= (int)$_ratingSummary; ?>%"
                                                                 class="rating-result">
                                                                <span
                                                                    style="width:<?= (int)$_ratingSummary; ?>%"><span><?= (int)$_ratingSummary; ?>%</span></span>
                                                            </div>
                                                        </div>
                                                        <div class="reviews-actions">
                                                            <?= $block->escapeHtml(__('(' . $_reviewCount . ')')); ?>
                                                        </div>
                                                    </div>
                                                <?php } ?>
                                                <?= /* @noEscape */
                                                $block->getPrice($_product) ?>
                                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                                    <div class="product-item-inner">
                                                        <div class="product-item-actions">
                                                            <?php if ($showCart): ?>
                                                                <div class="actions-primary">
                                                                    <?php if ($_product->isSaleable()): ?>
                                                                        <form data-role="tocart-form"
                                                                              action="<?= /* @noEscape */
                                                                                $postParams['action']; ?>" method="post">
                                                                            <input type="hidden" name="product"
                                                                                   value="<?= /* @noEscape */
                                                                                    $postParams['data']['product']; ?>">
                                                                            <input type="hidden"
                                                                                   name="<?= /* @noEscape */
                                                                                    $block->getCartParamNameURLEncoded(); ?>"
                                                                                   value="<?= /* @noEscape */
                                                                                    $postParams['data'][$block->getCartParamNameURLEncoded()]; ?>">
                                                                            <?= $block->getBlockHtml('formkey') ?>
                                                                            <button type="submit"
                                                                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')); ?>"
                                                                                    class="action tocart primary">
                                                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                            </button>
                                                                        </form>
                                                                    <?php else: ?>
                                                                        <?php if ($_product->getIsSalable()): ?>
                                                                            <div class="stock available">
                                                                                <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                                            </div>
                                                                        <?php else: ?>
                                                                            <div class="stock unavailable">
                                                                                <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                                            </div>
                                                                        <?php endif; ?>
                                                                    <?php endif; ?>
                                                                </div>
                                                            <?php endif ?>
                                                            <?php if ($showWishlist || $showCompare): ?>
                                                                <div class="actions-secondary" data-role="add-to-links">
                                                                    <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist): ?>
                                                                        <a href="#"
                                                                           accesskey="" data-post='<?= /* @noEscape */
                                                                            $this->helper(\Magento\Wishlist\Helper\Data::class)->getAddParams($_product) ?>'
                                                                           class="action towishlist"
                                                                           data-action="add-to-wishlist">
                                                                            <span><?= $block->escapeHtml(__('Add to Wish List')) ?>
                                                                        </a>
                                                                    <?php endif; ?>
                                                                    <?php if ($this->helper(\Magento\Catalog\Helper\Product\Compare::class) && $showCompare): ?>
                                                                        <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class); ?>
                                                                        <a href="#" class="action tocompare"
                                                                           data-post='<?= /* @noEscape */
                                                                            $compareHelper->getPostDataParams($_product) ?>'
                                                                           title="<?= /* @noEscape */
                                                                            __('Add to Compare') ?>">
                                                                            <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                                        </a>
                                                                    <?php endif; ?>
                                                                </div>
                                                            <?php endif ?>
                                                        </div>
                                                    </div>
                                                <?php endif ?>
                                            </div>
                                        </div>
                                    </li>
                                <?php endforeach ?>
                            </div>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {
               "bindSubmit": true
             }
        }
    }

    </script>
    <script type="text/x-magento-init">
    {
        "*": {
            "Risecommerce_FeaturedProducts/js/featuredproducts-slider": {}
        }
    }

    </script>
<?php endif; ?>
